import Link from "next/link";
import { DemoDrafts } from "@/components/demo-drafts";
import { getContentBank } from "@/lib/content-bank";
import { getSeries } from "@/lib/phase1-data";
import { getAppMode } from "@/lib/runtime-config";

const status: Record<string,string> = { READY: "準備完了", PLANNED: "企画済み", IDEA: "アイデア", DRAFT: "下書き", READY_FOR_REVIEW: "要確認", APPROVED: "承認済み", SCHEDULED: "投稿予定", PUBLISHING: "投稿中", PUBLISHED: "投稿済み", PUBLISH_FAILED: "再確認" };
function weekDates(){const formatter=new Intl.DateTimeFormat("ja-JP",{month:"numeric",day:"numeric",timeZone:"Asia/Tokyo"});const today=new Date();const start=new Date(today);const day=(today.getDay()+6)%7;start.setDate(today.getDate()-day);return Array.from({length:7},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);return{date,label:formatter.format(date),today:date.toDateString()===today.toDateString()}})}
export default async function OperatePage(){const[contentBank,series]=await Promise.all([getContentBank(),getSeries()]);const week=weekDates();const real=getAppMode()==="real";return <div className="page"><header><p className="eyebrow">OPERATE</p><h1 className="title">カレンダーと投稿</h1><p className="lead mt-3">作りかけ、予定、シリーズをひとつの場所で確認します。</p></header><section className="card mt-7 p-5 md:p-7"><div className="mb-5 flex items-center justify-between"><div><p className="eyebrow m-0">THIS WEEK</p><h2 className="mb-0 mt-2 text-xl">今週の予定</h2></div><span className="pill">{contentBank.filter((item)=>item.date!=="未定").length} / 4投稿</span></div><div className="grid grid-cols-7 gap-1 text-center text-xs text-[var(--muted)]">{week.map((entry,index)=><div key={entry.label}><span>{["月","火","水","木","金","土","日"][index]}</span><div className={`mx-auto mt-2 grid h-10 w-10 place-items-center rounded-full ${entry.today?"bg-[var(--sage-dark)] text-white":"bg-[var(--paper)]"}`}>{entry.label.split("/").at(-1)}</div></div>)}</div></section><div className="mt-5 grid gap-4 sm:grid-cols-2"><Link href="/create/ideas" className="soft-card p-5 text-[var(--ink)] no-underline"><p className="eyebrow m-0">IDEAS</p><h2 className="mb-1 mt-3 text-lg">アイデアを追加</h2><p className="m-0 text-sm text-[var(--muted)]">思いつきを次の投稿へ</p></Link><Link href="/operate/series" className="soft-card p-5 text-[var(--ink)] no-underline"><p className="eyebrow m-0">SERIES</p><h2 className="mb-1 mt-3 text-lg">シリーズ {series.length}件</h2><p className="m-0 text-sm text-[var(--muted)]">続きものの進捗を確認</p></Link></div><section className="mt-8"><div className="flex items-center justify-between"><h2 className="text-xl">コンテンツバンク</h2><span className="text-sm text-[var(--muted)]">{contentBank.length}件</span></div>{contentBank.length===0?<div className="card mt-3 p-6 text-center"><h3>まだ投稿がありません</h3><p className="text-sm text-[var(--muted)]">最初の投稿案をつくると、ここへ保存されます。</p><Link href="/create/reels" className="primary mt-2 no-underline">最初の投稿をつくる</Link></div>:<div className="grid gap-3">{contentBank.map((item)=>{const card=<><div className="grid h-16 w-14 shrink-0 place-items-center rounded-xl bg-[var(--apricot-soft)] text-xs font-bold">{item.type}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="pill">{status[item.status]??item.status}</span><span className="text-xs text-[var(--muted)]">{item.theme}</span></div><h3 className="mb-0 mt-2 truncate text-base">{item.title}</h3></div><span className="text-sm font-bold text-[var(--muted)]">{item.date}</span></>;return real?<Link href={`/operate/publish/${item.id}`} key={item.id} className="card flex items-center gap-4 p-4 text-[var(--ink)] no-underline md:p-5">{card}</Link>:<article key={item.id} className="card flex items-center gap-4 p-4 md:p-5">{card}</article>})}</div>}</section>{!real&&<DemoDrafts/>}</div>}
