"use client";

import { useState } from "react";
import Link from "next/link";
import type { IdeaRecord } from "@/lib/phase1-data";

export function IdeasManager({ initialIdeas, demo }: { initialIdeas: IdeaRecord[]; demo: boolean }) {
  const [ideas, setIdeas] = useState(initialIdeas); const [title, setTitle] = useState(""); const [topic, setTopic] = useState("首・肩"); const [objective, setObjective] = useState("GROWTH"); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function addIdea(event: React.FormEvent) { event.preventDefault(); if (!title.trim()) return; setSaving(true); setError(null); try { let created: IdeaRecord; if (demo) { created={id:crypto.randomUUID(),title:title.trim(),topic,objective,source:"手動",createdAt:new Date().toISOString()}; const rows=[created,...ideas]; localStorage.setItem("karadanojikan.phase1.ideas",JSON.stringify(rows)); } else { const response=await fetch("/api/ideas",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,topic,objective,source:"手動"})}); const data=await response.json() as Record<string,string>; if(!response.ok) throw new Error(data.error||"保存できませんでした。"); created={id:data.id??crypto.randomUUID(),title:data.title??title,topic:data.topic??topic,objective:data.objective??objective,source:data.source??"手動",createdAt:data.created_at??new Date().toISOString()}; } setIdeas((items)=>[created,...items]); setTitle(""); } catch(caught) { setError(caught instanceof Error?caught.message:"保存できませんでした。"); } finally { setSaving(false); } }
  return <><form onSubmit={addIdea} className="card mt-7 grid gap-4 p-5 md:grid-cols-2 md:p-7"><label className="font-bold md:col-span-2">アイデア<input value={title} onChange={(event)=>setTitle(event.target.value)} placeholder="例：肩だけ揉んでない？" maxLength={160} className="mt-2 block w-full rounded-xl border border-[var(--line)] p-3"/></label><label className="text-sm font-bold">テーマ<input value={topic} onChange={(event)=>setTopic(event.target.value)} maxLength={100} className="mt-2 block w-full rounded-xl border border-[var(--line)] p-3"/></label><label className="text-sm font-bold">目的<select value={objective} onChange={(event)=>setObjective(event.target.value)} className="mt-2 block w-full rounded-xl border border-[var(--line)] bg-white p-3"><option value="GROWTH">新規獲得</option><option value="TRUST">信頼</option><option value="LIFESTYLE">世界観</option><option value="CONVERSION">集客</option></select></label>{error&&<p role="alert" className="alert-card m-0 p-3 text-sm md:col-span-2">{error}</p>}<button disabled={saving||!title.trim()} className="primary md:col-span-2 md:justify-self-start">{saving?"保存中…":"アイデアを保存"}</button></form><section className="mt-8"><div className="flex items-center justify-between"><h2>保存したアイデア</h2><span className="pill">{ideas.length}件</span></div>{ideas.length===0?<div className="card p-6 text-center"><h3>まだアイデアがありません</h3><p className="text-sm text-[var(--muted)]">上の欄に一言だけでも保存できます。</p></div>:<div className="grid gap-3">{ideas.map((idea)=><article key={idea.id} className="card flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex gap-2"><span className="pill">{idea.objective}</span><span className="text-xs text-[var(--muted)]">{idea.topic}</span></div><h3 className="mb-0 mt-3">{idea.title}</h3></div><div className="flex gap-2"><Link href={`/create/reels?topic=${encodeURIComponent(idea.title)}`} className="secondary no-underline">Reels化</Link><Link href={`/create/carousel?topic=${encodeURIComponent(idea.title)}`} className="secondary no-underline">Carousel化</Link></div></article>)}</div>}</section></>;
}
