"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { GrowthExperimentRecord } from "@/lib/growth-data";

type Proposal = { title: string; hypothesis: string; variable: string; variantA: string; variantB: string; primaryMetric: string; minimumSampleSize: number };

export function InsightsActions({ canSync, proposal, sampleSize, experiments }: { canSync: boolean; proposal: Proposal; sampleSize: number; experiments: GrowthExperimentRecord[] }) {
  const router = useRouter(); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function sync() { setBusy("sync"); setMessage(null); setError(null); try { const response = await fetch("/api/instagram/insights/sync", { method: "POST" }); const result = await response.json() as { error?: string; mediaFound?: number; mediaMeasured?: number; status?: string }; if (!response.ok) throw new Error(result.error ?? "同期できませんでした。"); setMessage(`${result.mediaMeasured ?? 0}/${result.mediaFound ?? 0}件を取得しました。${result.status === "PARTIAL" ? "Metaの上限により一部のみです。" : ""}`); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "同期できませんでした。"); } finally { setBusy(null); } }
  async function saveProposal() { setBusy("proposal"); setMessage(null); setError(null); try { const response = await fetch("/api/growth/experiments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...proposal, evidence: { sampleSize, source: "OFFICIAL_INSTAGRAM_API", execution: "HUMAN_APPROVAL_REQUIRED" } }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error ?? "保存できませんでした。"); setMessage("実験案をPROPOSEDとして保存しました。投稿や戦略は変更していません。"); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "保存できませんでした。"); } finally { setBusy(null); } }
  async function decide(id: string, decision: "APPROVED" | "REJECTED") { setBusy(id); setMessage(null); setError(null); try { const response = await fetch(`/api/growth/experiments/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error ?? "更新できませんでした。"); setMessage(decision === "APPROVED" ? "検証計画を承認しました。投稿は実行されません。" : "実験案を見送りました。"); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "更新できませんでした。"); } finally { setBusy(null); } }
  return <div className="grid gap-5"><section className="card p-5 md:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow m-0">READ ONLY SYNC</p><h2 className="mb-1 mt-2 text-xl">公式APIから最新値を取得</h2><p className="m-0 text-sm leading-relaxed text-[var(--muted)]">直近25投稿を確認し、1回につき最大8投稿を手動測定します。未測定投稿を優先し、Metaへ投稿・返信・設定変更は行いません。</p></div><button className="primary shrink-0" disabled={!canSync || busy !== null} onClick={() => void sync()}>{busy === "sync" ? "取得中…" : "実測値を同期"}</button></div>{!canSync && <p className="alert-card mb-0 mt-4 p-3 text-sm">Instagram接続とInsights権限を確認してください。</p>}</section>
    <section className="card p-5 md:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="eyebrow m-0">CONTENT EXPERIMENT</p><h2 className="mb-2 mt-2 text-xl">{proposal.title}</h2><p className="m-0 text-sm leading-relaxed text-[var(--muted)]">{proposal.hypothesis}</p></div><button className="secondary shrink-0" disabled={busy !== null} onClick={() => void saveProposal()}>{busy === "proposal" ? "保存中…" : "実験案として保存"}</button></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="soft-card p-3 text-sm"><strong>変えるもの</strong><span className="mt-1 block">{proposal.variable}</span></div><div className="soft-card p-3 text-sm"><strong>A</strong><span className="mt-1 block">{proposal.variantA}</span></div><div className="soft-card p-3 text-sm"><strong>B</strong><span className="mt-1 block">{proposal.variantB}</span></div></div><p className="mb-0 mt-3 text-xs text-[var(--muted)]">主指標: {proposal.primaryMetric} · 最低{proposal.minimumSampleSize}件。保存しても投稿は行われません。</p></section>
    {experiments.length > 0 && <section><div className="mb-3 flex items-center justify-between"><h2 className="m-0 text-xl">保存した実験</h2><span className="pill">{experiments.length}件</span></div><div className="grid gap-3">{experiments.map((experiment) => <article className="card p-4" key={experiment.id}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><span className="pill">{experiment.status}</span><h3 className="mb-1 mt-3">{experiment.title}</h3><p className="m-0 text-sm text-[var(--muted)]">{experiment.variantA} / {experiment.variantB}</p></div>{experiment.status === "PROPOSED" && <div className="flex gap-2"><button className="secondary" disabled={busy !== null} onClick={() => void decide(experiment.id, "REJECTED")}>見送る</button><button className="primary min-h-12" disabled={busy !== null} onClick={() => void decide(experiment.id, "APPROVED")}>{busy === experiment.id ? "更新中…" : "計画を承認"}</button></div>}</div></article>)}</div></section>}
    {message && <p role="status" className="soft-card m-0 p-4 text-sm">{message}</p>}{error && <p role="alert" className="alert-card m-0 p-4 text-sm">{error}</p>}</div>;
}
