"use client";
import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Asset = { id:string; original_filename:string; media_type:string; byte_size:number; is_customer_media:boolean; rights:{ consent_status:string; approved_platforms:string[]; expires_at:string|null; music_license_status:string|null }|null };

export function InstagramPublishReview({ contentItemId, contentVersionId, contentType, caption, assets, defaultScheduledFor, connected, publishing }: {
  contentItemId:string; contentVersionId:string; contentType:string; caption:string; assets:Asset[]; defaultScheduledFor:string; connected:boolean; publishing:boolean;
}) {
  const [availableAssets,setAvailableAssets]=useState(assets);const [selected,setSelected]=useState<string[]>([]); const[scheduledFor,setScheduledFor]=useState(defaultScheduledFor); const[confirmed,setConfirmed]=useState(false); const[busy,setBusy]=useState(false); const[error,setError]=useState<string|null>(null); const[scheduleId,setScheduleId]=useState<string|null>(null); const[status,setStatus]=useState("READY_FOR_REVIEW");const[customerMedia,setCustomerMedia]=useState(false);const[customerConsent,setCustomerConsent]=useState(false);const[musicLicense,setMusicLicense]=useState("not_applicable");
  const eligible=useMemo(()=>availableAssets.filter((asset)=>!asset.is_customer_media||(asset.rights?.consent_status==="approved"&&asset.rights.approved_platforms.includes("instagram")&&(!asset.rights.expires_at||new Date(asset.rights.expires_at)>new Date()))),[availableAssets]);
  function toggle(id:string){setSelected((current)=>current.includes(id)?current.filter((value)=>value!==id):[...current,id]);}
  async function approve(){setBusy(true);setError(null);try{const response=await fetch("/api/instagram/schedules",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contentItemId,contentVersionId,scheduledFor:new Date(scheduledFor).toISOString(),mediaAssetIds:selected,confirmed,notes:"版・キャプション・素材・日時を画面で確認"})});const result=await response.json() as{error?:string;scheduleId?:string;status?:string};if(!response.ok||!result.scheduleId)throw new Error(result.error||"承認を保存できません。");setScheduleId(result.scheduleId);setStatus(result.status||"APPROVED");}catch(caught){setError(caught instanceof Error?caught.message:"承認を保存できません。");}finally{setBusy(false);}}
  async function enqueue(){if(!scheduleId)return;setBusy(true);setError(null);try{const response=await fetch(`/api/instagram/schedules/${scheduleId}/enqueue`,{method:"POST"});const result=await response.json() as{error?:string;status?:string};if(!response.ok)throw new Error(result.error||"キューに追加できません。");setStatus(result.status||"QUEUED");}catch(caught){setError(caught instanceof Error?caught.message:"キューに追加できません。");}finally{setBusy(false);}}
  async function upload(file:File|null){if(!file)return;setBusy(true);setError(null);try{if(customerMedia&&!customerConsent)throw new Error("お客様素材のInstagram利用同意を確認してください。");const rights={isCustomerMedia:customerMedia,consentStatus:customerMedia?"approved":"unknown",approvedPlatforms:customerMedia?["instagram"]:[],approvedUsage:customerMedia?["post"]:[],expiresAt:null,musicLicenseStatus:musicLicense};const response=await fetch("/api/instagram/media/uploads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({filename:file.name,contentType:file.type,byteSize:file.size,rights})});const result=await response.json() as{error?:string;assetId?:string;path?:string;token?:string};if(!response.ok||!result.assetId||!result.path||!result.token)throw new Error(result.error||"アップロードを準備できません。");const{error:uploadError}=await createClient().storage.from("publish-assets").uploadToSignedUrl(result.path,result.token,file,{contentType:file.type});if(uploadError)throw uploadError;const newAsset:Asset={id:result.assetId,original_filename:file.name,media_type:file.type,byte_size:file.size,is_customer_media:customerMedia,rights:{consent_status:customerMedia?"approved":"unknown",approved_platforms:customerMedia?["instagram"]:[],expires_at:null,music_license_status:musicLicense}};setAvailableAssets((current)=>[newAsset,...current]);setSelected((current)=>[...current,result.assetId!]);}catch(caught){setError(caught instanceof Error?caught.message:"アップロードできません。");}finally{setBusy(false);}}
  return <div className="grid gap-5"><section className="card p-5 md:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow m-0">EXACT VERSION</p><h2 className="mb-0 mt-2 text-xl">{contentType} · {contentVersionId.slice(0,8)}</h2></div><span className="pill">{status}</span></div><label className="mt-5 block text-sm font-bold">承認対象のキャプション<textarea value={caption} readOnly rows={8} className="mt-2 w-full rounded-2xl border border-[var(--line)] bg-[var(--paper)] p-4 font-normal leading-relaxed"/></label></section>
    <section className="card p-5 md:p-7"><h2 className="mt-0 text-xl">投稿素材</h2><p className="text-sm text-[var(--muted)]">Reelsは動画1件、Carouselは2〜10件を選びます。お客様素材はInstagram利用同意が必要です。</p><div className="soft-card mb-4 p-4"><label className="primary cursor-pointer text-sm">JPEG・動画を追加<input type="file" accept="image/jpeg,video/mp4,video/quicktime,video/webm,video/x-m4v" className="sr-only" disabled={busy} onChange={(event)=>void upload(event.target.files?.[0]??null)}/></label><label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={customerMedia} onChange={(event)=>{setCustomerMedia(event.target.checked);setCustomerConsent(false);}}/><span>お客様が映る素材</span></label>{customerMedia&&<label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={customerConsent} onChange={(event)=>setCustomerConsent(event.target.checked)}/><span>Instagram投稿と編集の同意を確認済み</span></label>}<label className="mt-3 block text-sm font-bold">音源の権利<select value={musicLicense} onChange={(event)=>setMusicLicense(event.target.value)} className="mt-2 w-full rounded-xl border border-[var(--line)] bg-white p-3 font-normal"><option value="not_applicable">音源なし／該当なし</option><option value="approved">所有・ライセンス確認済み</option><option value="unknown">要確認</option></select></label></div><div className="grid gap-2">{eligible.map((asset)=><label key={asset.id} className="flex gap-3 rounded-xl border border-[var(--line)] p-3 text-sm"><input type="checkbox" checked={selected.includes(asset.id)} onChange={()=>toggle(asset.id)}/><span><strong className="block">{asset.original_filename}</strong><small className="text-[var(--muted)]">{asset.media_type} · {(Number(asset.byte_size)/1024/1024).toFixed(1)} MB</small></span></label>)}</div>{eligible.length===0&&<p className="alert-card p-3 text-sm">利用できる素材がありません。先に動画作成または権利確認を完了してください。</p>}</section>
    <section className="card p-5 md:p-7"><label className="block text-sm font-bold">投稿予定日時<input type="datetime-local" value={scheduledFor} onChange={(event)=>setScheduledFor(event.target.value)} className="mt-2 block w-full rounded-xl border border-[var(--line)] p-3"/></label><label className="mt-5 flex gap-3 rounded-xl bg-[var(--apricot-soft)] p-4 text-sm"><input type="checkbox" checked={confirmed} onChange={(event)=>setConfirmed(event.target.checked)}/><span><strong className="block">この版・キャプション・素材・日時で投稿することを確認しました</strong><small className="mt-1 block">AIやアプリが承認を代行することはありません。</small></span></label>{error&&<p role="alert" className="alert-card mt-4 p-3 text-sm">{error}</p>}<div className="mt-5 flex flex-col gap-3 sm:flex-row">{!scheduleId?<button className="primary" disabled={busy||!connected||!publishing||!confirmed||selected.length===0||!scheduledFor} onClick={()=>void approve()}>{busy?"保存中…":"この版を承認"}</button>:<button className="primary" disabled={busy||status==="QUEUED"} onClick={()=>void enqueue()}>{busy?"処理中…":status==="QUEUED"?"キュー追加済み":"承認済み投稿をキューへ"}</button>}</div>{(!connected||!publishing)&&<p className="mb-0 mt-3 text-xs text-[var(--danger)]">Instagram接続と投稿Capabilityの確認が必要です。</p>}</section>
  </div>;
}
