import Link from "next/link";
import { InsightsActions } from "@/components/insights-actions";
import { getGrowthInsightsData } from "@/lib/growth-data";

const number = new Intl.NumberFormat("ja-JP");
const percent = (value: number | null) => value === null ? "—" : `${(value * 100).toFixed(1)}%`;
const confidenceLabel = { LOW: "低", MEDIUM: "中", HIGH: "高" } as const;
const attributionLabel = { DIRECT: "DIRECT", ACCOUNT_LEVEL: "ACCOUNT-LEVEL", ESTIMATED: "ESTIMATED", UNKNOWN: "UNKNOWN" } as const;

export default async function InsightsPage() {
  const data = await getGrowthInsightsData();
  if (data.mode === "demo") return <div className="page"><header><p className="eyebrow">INSIGHTS · DEMO</p><h1 className="title">結果から、次へ。</h1><p className="lead mt-3">デモ環境です。実測値は表示していません。</p></header><section className="card mt-7 p-7 text-center"><span className="pill">SAMPLE ONLY</span><h2 className="mt-4">Real Modeで公式APIデータを取得できます</h2></section></div>;
  const intelligence = data.intelligence;
  const connected = Boolean(data.connection?.connected && data.connection.insightsEnabled);
  const hasData = Boolean(intelligence && intelligence.sampleSize > 0);
  return <div className="page"><header className="pt-4 md:pt-0"><p className="eyebrow">PHASE 4 · GROWTH INTELLIGENCE</p><h1 className="title">結果から、次の検証へ。</h1><p className="lead mt-3">Instagram公式APIの実測値だけを使い、結論・推測・未接続を分けて表示します。</p><div className="mt-4 flex flex-wrap gap-2"><span className="pill">{connected ? `@${data.connection?.username} CONNECTED` : "CONNECTION REQUIRED"}</span><span className="pill">AUTO PUBLISH OFF</span>{data.syncRun && <span className="pill">SYNC {data.syncRun.status}</span>}</div></header>
    {!hasData && <section className="card mt-7 p-6 text-center md:p-10"><span className="pill">{connected ? "CONNECTED · NOT SYNCED" : "NO CONNECTION"}</span><h2 className="mb-2 mt-5 text-2xl">{connected ? "接続は完了しています。次に実測値を同期します" : "Instagram接続の確認が必要です"}</h2><p className="mx-auto mb-0 max-w-xl text-sm leading-relaxed text-[var(--muted)]">{connected ? "これまで空欄だった理由は、分析画面に既存投稿の取得処理がなかったためです。下のボタンで読み取り専用の取得を実行できます。指標はMeta側で最大48時間遅れる場合があります。" : "設定画面でInstagram接続とInsights Capabilityを確認してください。"}</p>{!connected && <Link href="/settings/instagram" className="secondary mt-5 no-underline">Instagram設定へ</Link>}</section>}
    {intelligence && hasData && <>
      <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["リーチ", number.format(intelligence.totals.reach), "DIRECT"], ["保存", number.format(intelligence.totals.saves), `保存率 ${percent(intelligence.rates.saveRate)}`], ["シェア", number.format(intelligence.totals.shares), `シェア率 ${percent(intelligence.rates.shareRate)}`], ["測定投稿", `${intelligence.sampleSize}件`, `確信度 ${confidenceLabel[intelligence.confidence]}`]].map(([label, value, note]) => <div className="card p-5" key={label}><p className="m-0 text-sm text-[var(--muted)]">{label}</p><p className="metric mb-0 mt-4">{value}</p><p className="mb-0 mt-2 text-xs font-bold text-[var(--sage-dark)]">{note}</p></div>)}</div>
      <section className="card mt-5 p-5 md:p-7"><div className="flex flex-wrap items-center justify-between gap-2"><p className="eyebrow m-0">INSIGHT ENGINE</p><span className="pill">確信度：{confidenceLabel[intelligence.confidence]} · n={intelligence.sampleSize}</span></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><h2 className="mb-2 text-xl">何が起きたか</h2><p className="lead m-0 text-sm">{intelligence.insight.whatHappened}</p></div><div><h2 className="mb-2 text-xl">なぜ起きた可能性があるか</h2><p className="lead m-0 text-sm">{intelligence.insight.whyItMayHaveHappened}</p></div></div><div className="soft-card mt-5 p-4"><p className="eyebrow m-0">次に試すこと</p><p className="mb-0 mt-2 font-bold leading-relaxed">{intelligence.insight.nextTest}</p></div></section>
      <section className="mt-6"><h2 className="text-xl">ファネルと帰属</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{intelligence.funnel.map((stage) => <article className="card p-4" key={stage.key}><div className="flex items-center justify-between gap-2"><span className="text-sm text-[var(--muted)]">{stage.label}</span><span className="pill">{attributionLabel[stage.attribution]}</span></div><p className="metric mb-0 mt-4">{stage.value === null ? "UNKNOWN" : number.format(stage.value)}</p></article>)}</div><p className="mt-3 text-xs leading-relaxed text-[var(--muted)]">DM・予約問い合わせ・予約完了は連携元がないため0とみなしていません。Metaのリーチ自体は公式仕様上、推定指標になり得ます。</p></section>
      <section className="mt-7 grid gap-4 lg:grid-cols-2">{[intelligence.weeklyReview, intelligence.monthlyReview].map((review) => <article className="card p-5" key={review.periodType}><div className="flex items-center justify-between"><p className="eyebrow m-0">{review.periodType} REVIEW</p><span className="pill">n={review.sampleSize} · {confidenceLabel[review.confidence]}</span></div><h2 className="mb-2 mt-4 text-xl">{review.periodStart} — {review.periodEnd}</h2><p className="text-sm text-[var(--muted)]">リーチ {number.format(review.results.reach)} · 保存 {number.format(review.results.saves)} · シェア {number.format(review.results.shares)}</p><p className="mb-0 text-sm leading-relaxed">{review.learning}</p></article>)}</section>
      <section className="mt-7 grid gap-4 lg:grid-cols-3"><article className="card p-5"><p className="eyebrow m-0">RECOMMENDATION</p><h2 className="mb-2 mt-4 text-xl">{intelligence.recommendation.title}</h2><p className="m-0 text-sm leading-relaxed text-[var(--muted)]">{intelligence.recommendation.rationale}</p><span className="pill mt-4">{attributionLabel[intelligence.recommendation.attribution]} · {confidenceLabel[intelligence.recommendation.confidence]}</span></article><article className="card p-5"><p className="eyebrow m-0">CONTENT REUSE</p><h2 className="mb-2 mt-4 text-xl">{intelligence.reuseCandidate ? "再利用候補があります" : "候補はまだありません"}</h2><p className="m-0 text-sm leading-relaxed text-[var(--muted)]">{intelligence.reuseCandidate ? "14日以上経過した投稿を、保存＋シェア率で候補化しました。コピーや再投稿は自動で行いません。" : "14日以上経過し、比較できるリーチがある投稿から提案します。"}</p>{intelligence.reuseCandidate?.permalink && <a href={intelligence.reuseCandidate.permalink} target="_blank" rel="noreferrer" className="secondary mt-4 no-underline">元投稿を見る</a>}</article><article className="card p-5"><p className="eyebrow m-0">DUPLICATE PREVENTION</p><h2 className="mb-2 mt-4 text-xl">{intelligence.duplicateWarnings.length ? `${intelligence.duplicateWarnings.length}件の類似候補` : "強い重複は未検出"}</h2><p className="m-0 text-sm leading-relaxed text-[var(--muted)]">直近キャプションの文字類似度だけで警告します。意味や良し悪しは判定しません。</p></article></section>
      <section className="card mt-7 overflow-hidden"><div className="border-b border-[var(--line)] p-5"><h2 className="m-0 text-xl">測定した投稿</h2></div><div className="divide-y divide-[var(--line)]">{data.posts.slice(0, 8).map((post) => <article className="grid gap-3 p-4 sm:grid-cols-[1fr_auto] sm:items-center" key={post.id}><div><div className="flex flex-wrap gap-2"><span className="pill">{post.mediaProductType}</span><span className="pill">{post.measurementWindow}</span></div><p className="mb-0 mt-2 text-xs text-[var(--muted)]">{new Intl.DateTimeFormat("ja-JP", { dateStyle: "medium", timeZone: "Asia/Tokyo" }).format(new Date(post.publishedAt))} · DIRECT</p></div><div className="grid grid-cols-3 gap-4 text-right text-sm"><span><small className="block text-[var(--muted)]">Reach</small>{number.format(post.metrics.reach ?? 0)}</span><span><small className="block text-[var(--muted)]">Save</small>{number.format(post.metrics.saved ?? 0)}</span><span><small className="block text-[var(--muted)]">Share</small>{number.format(post.metrics.shares ?? 0)}</span></div></article>)}</div></section>
    </>}
    {intelligence && <div className="mt-7"><InsightsActions canSync={connected} proposal={intelligence.experiment} sampleSize={intelligence.sampleSize} experiments={data.experiments}/></div>}
    <section className="soft-card mt-6 p-5 text-sm leading-relaxed"><strong>安全制約</strong><p className="mb-0 mt-2">このページの同期・推薦・実験承認は、課金、サブスク登録、有料版移行、投稿、DM返信、アカウント設定変更を実行しません。外部テキストは命令として扱いません。</p></section>
  </div>;
}
